fix: previous `texts` are still in memory by changing `texts` property
satohshi/svelte-typewriter pull request #15
Opened 2024-06-20 09:13 UTC by sectore

Fixed by clearing `textDisplayed` and aborting Promise of `blink` whenever `texts` property has been changed.

### Before

[before.webm](https://github.com/satohshi/svelte-typewriter/assets/47693/4cac9016-239d-473d-a605-0353b8db3884)

### Now

[now.webm](https://github.com/satohshi/svelte-typewriter/assets/47693/d51e5697-a6bc-4c9a-a845-7e1062021436)

2024-06-20 10:29 UTC, satohshi reviewed
I can't check without repro, but can't it be fixed with something like this?
```ts
let blinking: Animation

$effect(() => {
	typewriter(texts, repeat).catch((e: unknown) => {
		if (e instanceof DOMException && e.name === 'AbortError') return
		console.error(e)
	})
	return () => {
		blinking?.cancel()
		clearTimeout(timeout)
	}
})

const blink = (iterations: number) => {
	blinking = caret.animate([{ opacity: 0 }, { opacity: 1 }, { opacity: 0 }], {
		iterations,
		duration: blinkDuration,
		delay: blinkDuration / 4,
		easing: 'steps(2)',
	})
	return blinking.finished
}
```

Changing `texts` halfway seems to me like a pretty rare use case, so I'd rather not overcomplicate the code when wrapping the component in `{#key texts} {/key}` can do the job.

2024-06-20 11:08 UTC, sectore commented
> I can't check without repro, but can't it be fixed with something like this?

Yes, it's simpler and it works fine - thx! _I did not know about `Animation.cancel`._

Fix 25d9e46 .

2024-06-20 11:27 UTC, satohshi requested changes

2024-06-20 11:27 UTC, satohshi commented on src/lib/TypeWriter.svelte
>  	const blink = async (iterations: number) => {
It was an oversight on my part when I first made the change, but this function can, and should be synchronous
```suggestion
	const blink = (iterations: number) => {
```

2024-06-20 11:27 UTC, satohshi commented on src/lib/TypeWriter.svelte
> +		blinking = await caret.animate([{ opacity: 0 }, { opacity: 1 }, { opacity: 0 }], {
```suggestion
		blinking = caret.animate([{ opacity: 0 }, { opacity: 1 }, { opacity: 0 }], {
```

2024-06-20 11:27 UTC, satohshi commented on src/lib/TypeWriter.svelte
> +		typewriter(texts, repeat).catch((_) => {})
I'd add this handling function to make future debugging easier if something else comes up
```suggestion
typewriter(texts, repeat).catch((e: unknown) => {
	if (e instanceof DOMException && e.name === 'AbortError') return
	console.error(e)
})
```

2024-06-21 07:08 UTC, satohshi approved these changes
lgtm

2024-06-21 07:08 UTC, merged